=== Jenner4S/unitimes/src/main/webapp/help/Release-Notes.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->

<!ELEMENT release-history (doc-title,release+)>

<!ELEMENT doc-title (#PCDATA)>

<!ELEMENT release (version,release-date,category+)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT release-date (#PCDATA)>

<!ELEMENT category (title,item+)>
<!ELEMENT title (#PCDATA)>

<!ELEMENT item (name,description)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT description (line+)>
<!ELEMENT line (#PCDATA|line)*>

=== Jenner4S/unitimes/src/main/webapp/help/Release-Notes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/css" href="Release-Notes.css"?>
<!DOCTYPE release-history PUBLIC "-//UniTime//UniTime Release Notes DTD/EN" "Release-Notes.dtd">
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->

<release-history>

<doc-title>UniTime 4.2 Release Notes</doc-title>
<release>
	<version>4.2.${build.number}</version>
	<release-date>${build.date}</release-date>
	<category>
		<title>Course Timetabling</title>
		<item>
			<name>Room Edit: Google Map</name>
			<description>
				<line>When user cannot edit room coordinates: show marker that cannot be moved around.</line>
				<line>When user cannot edit room coordinates and there are no coordinates: do not show the map at all.</line>
			</description>
		</item>
		<item>
			<name>Longer Class Suffix and Configuration Name</name>
			<description>
				<line>Class suffix and configuration name fields are now up to 20 characters long (instead of 10).</line>
			</description>
		</item>
		<item>
			<name>Configuration Names</name>
			<description>
				<line>When the application property unitime.solver.showConfigurationNames is set to true (defaults to false), configuration name is added to the class name when the data are being loaded into the course timetabling solver.</line>
				<line>This is only done when the course has two or more configurations.</line>
			</description>
		</item>
		<item>
			<name>Reservations</name>
			<description>
				<line>Added ability to consider reservations that are set on other problems (on committed classes).</line>
				<line>To enable this feature, set solver parameter General.LoadCommittedReservations to true.</line>
			</description>
		</item>
		<item>
			<name>Instructional Offering Detail, Class Detail: Class/Offering Conflicts</name>
			<description>
				<line>If an instructor is assigned to a class two (or more) times with different responsibility, do not show that as an instructor conflict.</line>
				<line>Only show an instructor conflict between two classes, if the instructor is lead on both classes.</line>
			</description>
		</item>
		<item>
			<name>Last-Like Student Course Demands</name>
			<description>
				<line>Added ability to consider last-like student course demand priorities.</line>
				<line>Enable using solver parameter LastLikeStudentCourseDemands.UsePriorities = true (defaults to false).</line>
				<line>Enrollment importance is computed as base ^ priority.
					<line>Where base is defined using solver parameter LastLikeStudentCourseDemands.BasePriorityWeight, defaults to 0.9.</line>
					<line>Priority 0 has importance of 1.0, priority 1 of 0.9, priority 2 of 0.9^2 = 0.81, etc.</line>
				</line>
			</description>
		</item>
		<item>
			<name>Solver Page</name>
			<description>
				<line>Parameters: Recognize &quot;on&quot; as a true value for boolean parameters.</line>
				<line>Interactive: When an interactive configuration is used (the solver was loaded on the Timetables page),
					make sure that the configuration that is being used is available in the Solver Configuration drop down.
					<line>This also fixes an issue of an unwanted configuration change when the solver is reloaded on the Solver page.</line>
				</line>
			</description>
		</item>
	</category>
	<category>
		<title>Online Student Scheduling</title>
		<item>
			<name>Custom Student Enrollment Provider: Enroll Student</name>
			<description>
				<line>Avoid creating additional course requests for the same course when the custom student enrollment provider refuses to drop a course.</line>
			</description>
		</item>
		<item>
			<name>Online Student Scheduling Server: Release Master Lock</name>
			<description>
				<line>When there is no solver cluster (online student scheduling server runs within the Tomcat and there is no master lock), reload the server when requested.</line>
				<line>This fixes an issue on the Manage Solvers page where the online scheduling server cannot be reloaded when the server is running locally (there is no cluster).</line>
			</description>
		</item>
		<item>
			<name>Teaching Assignments</name>
			<description>
				<line>Instructor assignments that do not check conflicts (Check Conflicts toggle is not checked) can overlap with class enrollments.</line>
			</description>
		</item>
		<item>
			<name>Course Requests: Eligibility Check</name>
			<description>
				<line>Allow for collecting registrations when the academic status does not have any default student status selected (all should be enabled).</line>
			</description>
		</item>
	</category>
	<category>
		<title>Batch Student Scheduling</title>
		<item>
			<name>Student Scheduling Solver: Save</name>
			<description>
				<line>There is a new permission named Student Sectioning Solver Save that can be used to restrict who can save the student class enrollments.</line>
				<line>By default, the Student Sectioning Solver Save permission is given to the role that have Student Sectioning Solver permission (that is all the roles, that can use the solver page).</line>
			</description>
		</item>
	</category>
	<category>
		<title>Instructor Scheduling</title>
		<item>
			<name>Setup Teaching Requests</name>
			<description>
				<line>Do not show course title if it is not set (null).</line>
				<line>Show Include Subparts section even when there is only one subpart to show (it may be still important to set percentage share etc.).</line>
			</description>
		</item>
	</category>
	<category>
		<title>Event Management</title>
		<item>
			<name>Rooms: Export PDF/CSV</name>
			<description>
				<line>Event status may contain line breaks -- change &lt;br&gt; to a new line.</line>
			</description>
		</item>
		<item>
			<name>Room Pictures: Sorting</name>
			<description>
				<line>Compare room pictures with the same time stamp by name and/or unique id.
					<line>This fixes an issue of not showing some pictures if they have the same time stamp.</line>
				</line>
			</description>
		</item>
		<item>
			<name>Curriculum Timetable: Multiple Majors</name>
			<description>
				<line>Include inherited courses when showing a multiple-major curriculum, do not show courses with zero percent share.</line>
			</description>
		</item>
	</category>
	<category>
	    <title>Administration</title>
	    <item>
	        <name>Data Exchange: Academic Session Setup</name>
	        <description>
	            <line>Added and XML import/export that can
	                <line>Create or update academic session (dates and holidays)</line>
	                <line>Import or update departments, subject areas, managers, solver groups, date patterns, time patterns, examination periods,
	                    academic areas, academic classifications, majors, minors, student groups, and/or student accomodations.</line>
	                <line>The import can contain only certain sections (e.g., only date and time patterns).</line>
	                <line>All items can be imported in an incremental mode (entities that are not present in the file are ignored). By default, entities that are not present in the file are deleted.</line>
	            </line>
	        </description>
	    </item>
	    <item>
	    	<name>Data Exchange: Course Offering Import</name>
	    	<description>
	    		<line>In the incremental mode (incremental=&quot;true&quot;), do not delete configurations, subparts, or classes when there are no config, subpart, or class elements present.</line>
	    		<line>Also, do not change credit or consent information when the course has no courseCredit or consent element respectively.</line>
	    		<line>Staff lookup: avoid exceptions when the same person is listed under multiple departments, lookup under the controlling department first.</line>
	    	</description>
	    </item>
	    <item>
	    	<name>Data Exchange: Course Timetable/Offerings XML Export</name>
	    	<description>
	    		<line>Added ability to export student group assignments with the assignment (enable by setting tmtbl.export.studentGroups to true, defaults to false).</line>
	    	</description>
	    </item>
	    <item>
	    	<name>HQL Reports: Navigation</name>
	    	<description>
	    		<line>Show Previous/Next buttons at the bottom of the page (below the table) too.</line>
	    	</description>
	    </item>
	</category>
</release>
<release>
	<version>4.2.154</version>
	<release-date>Wed, 21 Jun 2017</release-date>
	<category>
		<title>First Release of UniTime 4.2 (planned June 2017)</title>
		<item>
			<name>Release Notes</name>
			<description>
				<line>See https://goo.gl/4g1XQV for more details.</line>
			</description>
		</item>
	</category>
	<category>
		<title>Instructor Scheduling</title>
		<item>
			<name>Description</name>
			<description>
				<line>In UniTime 4.2, a new component for automatic assignment of instructors to classes or courses has been created.</line>
				<line>The instructors (e.g., teaching assistants) are expected to be assigned after the course timetabling and student
					scheduling are done, using information from both course timetabling (course timetable) and student scheduling
					(student availability).</line>
				<line>See https://goo.gl/Zb2aES for more details.</line>
			</description>
		</item>
	</category>
