=== Jenner4S/unitimes/Documentation/Interfaces/AcademicSessionSetup.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->

<!ELEMENT sessionSetup ( session?, managers?, departments?, subjectAreas?, solverGroups?, datePatterns?, timePatterns?, examinationPeriods?, academicAreas?, academicClassifications?, posMajors?, posMinors?, studentGroups?, studentAccomodations? )  >
<!ATTLIST sessionSetup term CDATA #REQUIRED >
<!ATTLIST sessionSetup year CDATA #REQUIRED >
<!ATTLIST sessionSetup campus CDATA #REQUIRED >
<!ATTLIST sessionSetup dateFormat CDATA #IMPLIED >
<!ATTLIST sessionSetup created CDATA #IMPLIED >

<!ELEMENT session ( holidays? ) >
<!ATTLIST session startDate CDATA #REQUIRED >
<!ATTLIST session endDate CDATA #REQUIRED >
<!ATTLIST session classEndDate CDATA #REQUIRED >
<!ATTLIST session examStartDate CDATA #REQUIRED >
<!ATTLIST session eventStartDate CDATA #IMPLIED >
<!ATTLIST session eventEndDate CDATA #IMPLIED >

<!ELEMENT holidays ((holiday|break)*) >

<!ELEMENT holiday EMPTY >
<!ATTLIST holiday date CDATA #REQUIRED >

<!ELEMENT break EMPTY >
<!ATTLIST break date CDATA #IMPLIED >
<!ATTLIST break startDate CDATA #IMPLIED >
<!ATTLIST break endDate CDATA #IMPLIED >

<!ELEMENT managers ( manager* ) >
<!ATTLIST managers incremental ( false | true ) #IMPLIED >

<!ELEMENT manager ((department|role)*) >
<!ATTLIST manager externalId CDATA #REQUIRED >
<!ATTLIST manager firstName CDATA #IMPLIED >
<!ATTLIST manager middleName CDATA #IMPLIED >
<!ATTLIST manager lastName CDATA #IMPLIED >
<!ATTLIST manager acadTitle CDATA #IMPLIED >
<!ATTLIST manager email CDATA #IMPLIED >

<!ELEMENT department (externalManager?,eventManagement?,studentScheduling?,required?,instructorPreferences?,distributionPreferences?) >
<!ATTLIST department externalId CDATA #IMPLIED >
<!ATTLIST department code CDATA #REQUIRED >
<!ATTLIST department abbreviation CDATA #IMPLIED >
<!ATTLIST department name CDATA #IMPLIED >

<!ELEMENT role EMPTY >
<!ATTLIST role reference CDATA #REQUIRED >
<!ATTLIST role primary (true|false) #IMPLIED >
<!ATTLIST role emails (true|false) #IMPLIED >

<!ELEMENT departments ( department* ) >
<!ATTLIST departments incremental ( false | true ) #IMPLIED >

<!ELEMENT externalManager EMPTY>
<!ATTLIST externalManager enabled ( false | true ) #IMPLIED >
<!ATTLIST externalManager abbreviation CDATA #REQUIRED >
<!ATTLIST externalManager label CDATA #REQUIRED >

<!ELEMENT eventManagement EMPTY>
<!ATTLIST eventManagement enabled ( false | true ) #REQUIRED >

<!ELEMENT studentScheduling EMPTY>
<!ATTLIST studentScheduling enabled ( false | true ) #REQUIRED >

<!ELEMENT required EMPTY>
<!ATTLIST required time ( false | true ) #REQUIRED >
<!ATTLIST required room ( false | true ) #REQUIRED >
<!ATTLIST required distribution ( false | true ) #REQUIRED >

<!ELEMENT instructorPreferences EMPTY>
<!ATTLIST instructorPreferences inherit ( false | true ) #REQUIRED >

<!ELEMENT distributionPreferences EMPTY>
<!ATTLIST distributionPreferences priority CDATA #IMPLIED >

<!ELEMENT subjectAreas ( subjectArea* ) >
<!ATTLIST subjectAreas incremental ( false | true ) #IMPLIED >

<!ELEMENT subjectArea EMPTY>
<!ATTLIST subjectArea abbreviation CDATA #REQUIRED >
<!ATTLIST subjectArea externalId CDATA #IMPLIED >
<!ATTLIST subjectArea title CDATA #REQUIRED >
<!ATTLIST subjectArea department CDATA #REQUIRED >

<!ELEMENT solverGroups ( solverGroup* ) >
<!ATTLIST solverGroups incremental ( false | true ) #IMPLIED >

<!ELEMENT solverGroup ((manager|department)*) >
<!ATTLIST solverGroup abbreviation CDATA #REQUIRED >
<!ATTLIST solverGroup name CDATA #REQUIRED >

<!ELEMENT datePatterns ( datePattern* ) >
<!ATTLIST datePatterns incremental ( false | true ) #IMPLIED >

<!ELEMENT datePattern ((department|datePattern|dates)*) >
<!ATTLIST datePattern name CDATA #REQUIRED >
<!ATTLIST datePattern type CDATA #IMPLIED >
<!ATTLIST datePattern visible (true|false) #IMPLIED >
<!ATTLIST datePattern default (true|false) #IMPLIED >
<!ATTLIST datePattern nbrWeeks CDATA #IMPLIED >

<!ELEMENT dates EMPTY >
<!ATTLIST dates fromDate CDATA #IMPLIED >
<!ATTLIST dates toDate CDATA #IMPLIED >
<!ATTLIST dates date CDATA #IMPLIED >

<!ELEMENT timePatterns ( timePattern* ) >
<!ATTLIST timePatterns incremental ( false | true ) #IMPLIED >

<!ELEMENT timePattern ((department|days|time)*) >
<!ATTLIST timePattern name CDATA #REQUIRED >
<!ATTLIST timePattern type CDATA #REQUIRED >
<!ATTLIST timePattern nbrMeetings CDATA #REQUIRED >
<!ATTLIST timePattern minsPerMeeting CDATA #REQUIRED >
<!ATTLIST timePattern visible (true|false) #IMPLIED >
<!ATTLIST timePattern nbrSlotsPerMeeting CDATA #REQUIRED >
<!ATTLIST timePattern breakTime CDATA #IMPLIED >

<!ELEMENT days EMPTY >
<!ATTLIST days code CDATA #IMPLIED >

<!ELEMENT time EMPTY >
<!ATTLIST time start CDATA #IMPLIED >

<!ELEMENT examinationPeriods ( periods* ) >

<!ELEMENT periods (period*)>
<!ATTLIST periods type CDATA #REQUIRED >
<!ATTLIST periods incremental ( false | true ) #IMPLIED >

<!ELEMENT period EMPTY>
<!ATTLIST period date CDATA #REQUIRED >
<!ATTLIST period startTime CDATA #REQUIRED >
<!ATTLIST period length CDATA #REQUIRED >
<!ATTLIST period eventStartOffset CDATA #IMPLIED >
<!ATTLIST period eventStopOffset CDATA #IMPLIED >
<!ATTLIST period preference (-2|-1|0|1|2|P) #IMPLIED >

<!ELEMENT academicAreas (academicArea*)>
<!ATTLIST academicAreas incremental ( false | true ) #IMPLIED >

<!ELEMENT academicArea EMPTY>
<!ATTLIST academicArea externalId CDATA #IMPLIED >
<!ATTLIST academicArea abbreviation CDATA #REQUIRED >
<!ATTLIST academicArea title CDATA #REQUIRED >

<!ELEMENT academicClassifications (academicClassification*)>
<!ATTLIST academicClassifications incremental ( false | true ) #IMPLIED >

<!ELEMENT academicClassification EMPTY>
<!ATTLIST academicClassification externalId CDATA #IMPLIED >
<!ATTLIST academicClassification code CDATA #REQUIRED >
<!ATTLIST academicClassification name CDATA #REQUIRED >

<!ELEMENT posMajors (posMajor*)>
<!ATTLIST posMajors incremental ( false | true ) #IMPLIED >

<!ELEMENT posMajor EMPTY>
<!ATTLIST posMajor externalId CDATA #IMPLIED >
<!ATTLIST posMajor code CDATA #REQUIRED >
<!ATTLIST posMajor name CDATA #REQUIRED >
<!ATTLIST posMajor academicArea CDATA #REQUIRED >

<!ELEMENT posMinors (posMinor*)>
<!ATTLIST posMinors incremental ( false | true ) #IMPLIED >

<!ELEMENT posMinor EMPTY>
<!ATTLIST posMinor externalId CDATA #IMPLIED >
<!ATTLIST posMinor code CDATA #REQUIRED >
<!ATTLIST posMinor name CDATA #REQUIRED >
<!ATTLIST posMinor academicArea CDATA #REQUIRED >

<!ELEMENT studentGroups (studentGroup*)>
<!ATTLIST studentGroups incremental ( false | true ) #IMPLIED >

<!ELEMENT studentGroup EMPTY>
<!ATTLIST studentGroup externalId CDATA #IMPLIED >
<!ATTLIST studentGroup code CDATA #REQUIRED >
<!ATTLIST studentGroup name CDATA #REQUIRED >

<!ELEMENT studentAccomodations (studentAccomodation*)>
<!ATTLIST studentAccomodations incremental ( false | true ) #IMPLIED >

<!ELEMENT studentAccomodation EMPTY>
<!ATTLIST studentAccomodation externalId CDATA #IMPLIED >
<!ATTLIST studentAccomodation code CDATA #REQUIRED >
<!ATTLIST studentAccomodation name CDATA #REQUIRED >

=== Jenner4S/unitimes/Documentation/Interfaces/Examples/sessionSetup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sessionSetup PUBLIC "-//UniTime//UniTime Academic Session Setup/EN" "http://www.unitime.org/interface/AcademicSessionSetup.dtd">
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
<sessionSetup term="Fal" year="2010" campus="TEST" dateFormat="yyyy/M/d" created="Fri Jun 23 15:21:28 CEST 2017">
  <!-- Element session is optional, needed to create and/or update acedemic session information -->
  <session startDate="2010/8/23" endDate="2010/12/19" classEndDate="2010/12/12" examStartDate="2010/12/13" eventStartDate="2010/7/19" eventEndDate="2011/1/16">
    <holidays>
      <holiday date="2010/9/6"/>
      <break startDate="2010/10/11" endDate="2010/10/12"/>
      <break startDate="2010/11/24" endDate="2010/11/27"/>
    </holidays>
  </session>
  <!-- Element managers is optional, needed to create/update timetable managers (when incremental=true, managers not present in this file will not be deleted) -->
  <managers incremental="true">
    <manager externalId="7" firstName="Manager" lastName="Curriculum" email="demo@unitime.org">
      <department code="0101"/>
      <role reference="Curriculum Mgr" primary="true" emails="true"/>
    </manager>
    <manager externalId="4" firstName="Schedule" lastName="Deputy" email="demo@unitime.org">
      <department code="0101"/>
      <role reference="Dept Sched Mgr" primary="true" emails="true"/>
    </manager>
    <manager externalId="2" firstName="Adam" lastName="Guest" email="demo@unitime.org">
      <department code="0102"/>
      <role reference="View All" primary="true" emails="true"/>
    </manager>
    <manager externalId="6" firstName="Event" lastName="Manager" email="demo@unitime.org">
      <department code="0101"/>
      <department code="0100"/>
      <department code="0102"/>
      <role reference="Event Mgr" primary="true" emails="true"/>
    </manager>
    <manager externalId="3" firstName="Large" middleName="Lecture" lastName="Room" email="demo@unitime.org">
      <department code="0100"/>
      <role reference="Dept Sched Mgr" primary="true" emails="true"/>
    </manager>
    <manager externalId="1" firstName="Abraham" lastName="Root" email="demo@unitime.org">
      <department code="0100"/>
      <role reference="Administrator" primary="true" emails="true"/>
    </manager>
  </managers>
  <departments>
    <department code="0101" externalId="Woebegon Dept 0101" abbreviation="Instr" name="Student Instructional Planning">
      <eventManagement enabled="true"/>
      <required time="false" room="false" distribution="false"/>
      <instructorPreferences inherit="true"/>
    </department>
    <department code="0102" abbreviation="Adm" name="Admission Office">
      <eventManagement enabled="true"/>
      <required time="false" room="false" distribution="false"/>
      <instructorPreferences inherit="true"/>
    </department>
    <department code="0100" abbreviation="Centr" name="Central Office">
      <externalManager enabled="true" abbreviation="LLR" label="Large Lecture Room"/>
      <eventManagement enabled="true"/>
      <required time="false" room="false" distribution="false"/>
      <distributionPreferences priority="-1"/>
    </department>
  </departments>
  <subjectAreas>
    <subjectArea abbreviation="ALG" title="Algebra" department="0101"/>
    <subjectArea abbreviation="BAND" title="Band" department="0101"/>
    <subjectArea abbreviation="BIOL" title="Biology" department="0101"/>
    <subjectArea abbreviation="CALC" title="Calculus" department="0101"/>
    <subjectArea abbreviation="CHIN" title="Chinese" department="0101"/>
    <subjectArea abbreviation="CHM" title="Chemistry" department="0101"/>
    <subjectArea abbreviation="COM" title="Communications" department="0101"/>
    <subjectArea abbreviation="C S" title="Computer Science" department="0101"/>
    <subjectArea abbreviation="ECON" title="Economics" department="0101"/>
    <subjectArea abbreviation="ENGL" title="English" department="0101"/>
    <subjectArea abbreviation="ENGR" title="Engineering" department="0101"/>
    <subjectArea abbreviation="GER" title="German" department="0101"/>
    <subjectArea abbreviation="HIST" title="History" department="0101"/>
    <subjectArea abbreviation="LING" title="Linguistics" department="0101"/>
    <subjectArea abbreviation="MBIO" title="Microbiology" department="0101"/>
    <subjectArea abbreviation="PHAR" title="Pharmacy" department="0101"/>
    <subjectArea abbreviation="PHIL" title="Philosophy" department="0101"/>
    <subjectArea abbreviation="PHYS" title="Physics" department="0101"/>
    <subjectArea abbreviation="POL" title="Political Science" department="0101"/>
    <subjectArea abbreviation="PSY" title="Psychology" department="0101"/>
    <subjectArea abbreviation="SOC" title="Solciology" department="0101"/>
    <subjectArea abbreviation="SPAN" title="Spanish" department="0101"/>
  </subjectAreas>
  <solverGroups>
    <solverGroup abbreviation="Instr Plan" name="Instructional Planning">
      <manager externalId="4"/>
      <department code="0101"/>
    </solverGroup>
    <solverGroup abbreviation="LLR" name="Large Lecture Room">
      <manager externalId="3"/>
      <department code="0100"/>
    </solverGroup>
  </solverGroups>
  <datePatterns>
    <datePattern name="Full Term" type="Standard" visible="true" default="true">
      <dates fromDate="2010/8/23" toDate="2010/8/28"/>
      <dates fromDate="2010/8/30" toDate="2010/9/4"/>
      <dates fromDate="2010/9/7" toDate="2010/9/11"/>
      <dates fromDate="2010/9/13" toDate="2010/9/18"/>
      <dates fromDate="2010/9/20" toDate="2010/9/25"/>
      <dates fromDate="2010/9/27" toDate="2010/10/2"/>
      <dates fromDate="2010/10/4" toDate="2010/10/9"/>
      <dates fromDate="2010/10/13" toDate="2010/10/16"/>
      <dates fromDate="2010/10/18" toDate="2010/10/23"/>
      <dates fromDate="2010/10/25" toDate="2010/10/30"/>
      <dates fromDate="2010/11/1" toDate="2010/11/6"/>
      <dates fromDate="2010/11/8" toDate="2010/11/13"/>
      <dates fromDate="2010/11/15" toDate="2010/11/20"/>
      <dates fromDate="2010/11/22" toDate="2010/11/23"/>
      <dates fromDate="2010/11/29" toDate="2010/12/4"/>
      <dates fromDate="2010/12/6" toDate="2010/12/11"/>
    </datePattern>
    <datePattern name="Week 1-10" type="Standard" visible="true" default="false">
      <dates fromDate="2010/8/23" toDate="2010/8/28"/>
      <dates fromDate="2010/8/30" toDate="2010/9/4"/>
      <dates fromDate="2010/9/7" toDate="2010/9/11"/>
      <dates fromDate="2010/9/13" toDate="2010/9/18"/>
      <dates fromDate="2010/9/20" toDate="2010/9/25"/>
      <dates fromDate="2010/9/27" toDate="2010/10/2"/>
      <dates fromDate="2010/10/4" toDate="2010/10/9"/>
      <dates fromDate="2010/10/13" toDate="2010/10/16"/>
      <dates fromDate="2010/10/18" toDate="2010/10/23"/>
      <dates fromDate="2010/10/25" toDate="2010/10/30"/>
      <dates fromDate="2010/11/1" toDate="2010/11/2"/>
    </datePattern>
    <datePattern name="Week 6-15" type="Standard" visible="true" default="false">
      <dates fromDate="2010/9/27" toDate="2010/10/2"/>
      <dates fromDate="2010/10/4" toDate="2010/10/9"/>
      <dates fromDate="2010/10/13" toDate="2010/10/16"/>
      <dates fromDate="2010/10/18" toDate="2010/10/23"/>
      <dates fromDate="2010/10/25" toDate="2010/10/30"/>
      <dates fromDate="2010/11/1" toDate="2010/11/6"/>
      <dates fromDate="2010/11/8" toDate="2010/11/13"/>
      <dates fromDate="2010/11/15" toDate="2010/11/20"/>
      <dates fromDate="2010/11/22" toDate="2010/11/23"/>
      <dates fromDate="2010/11/29" toDate="2010/12/4"/>
      <dates fromDate="2010/12/6" toDate="2010/12/11"/>
    </datePattern>
    <datePattern name="Week 1-8" type="Standard" visible="true" default="false">
      <dates fromDate="2010/8/23" toDate="2010/8/28"/>
      <dates fromDate="2010/8/30" toDate="2010/9/4"/>
      <dates fromDate="2010/9/7" toDate="2010/9/11"/>
      <dates fromDate="2010/9/13" toDate="2010/9/18"/>
      <dates fromDate="2010/9/20" toDate="2010/9/25"/>
      <dates fromDate="2010/9/27" toDate="2010/10/2"/>
      <dates fromDate="2010/10/4" toDate="2010/10/9"/>
      <dates fromDate="2010/10/13" toDate="2010/10/16"/>
      <dates fromDate="2010/10/18" toDate="2010/10/19"/>
    </datePattern>
    <datePattern name="Week 9-15" type="Standard" visible="true" default="false">
      <dates fromDate="2010/10/20" toDate="2010/10/23"/>
      <dates fromDate="2010/10/25" toDate="2010/10/30"/>
      <dates fromDate="2010/11/1" toDate="2010/11/6"/>
      <dates fromDate="2010/11/8" toDate="2010/11/13"/>
      <dates fromDate="2010/11/15" toDate="2010/11/20"/>
      <dates fromDate="2010/11/22" toDate="2010/11/23"/>
      <dates fromDate="2010/11/29" toDate="2010/12/4"/>
      <dates fromDate="2010/12/6" toDate="2010/12/11"/>
    </datePattern>
    <datePattern name="Week 1-5" type="Standard" visible="true" default="false">
      <dates fromDate="2010/8/23" toDate="2010/8/28"/>
      <dates fromDate="2010/8/30" toDate="2010/9/4"/>
      <dates fromDate="2010/9/7" toDate="2010/9/11"/>
      <dates fromDate="2010/9/13" toDate="2010/9/18"/>
      <dates fromDate="2010/9/20" toDate="2010/9/25"/>
    </datePattern>
