=== Jenner4S/unitimes/Documentation/Interfaces/CourseCatalog.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->

<!ELEMENT course ( courseCredit, subpartCredit* ) >
<!ATTLIST course approvalType ( department | instructor | timeblock ) #IMPLIED >
<!ATTLIST course courseNumber CDATA #REQUIRED >
<!-- designatorRequired toggle is deprecated since UniTime 3.4, it was required in UniTime 3.3 or earlier -->
<!ATTLIST course designatorRequired ( false | False | true | True ) #IMPLIED >
<!ATTLIST course externalId CDATA #IMPLIED >
<!ATTLIST course permanentId CDATA #IMPLIED >
<!ATTLIST course previousCourseNumber CDATA #IMPLIED >
<!ATTLIST course previousSubject CDATA #IMPLIED >
<!ATTLIST course subject CDATA #REQUIRED >
<!ATTLIST course title CDATA #REQUIRED >

<!ELEMENT courseCatalog ( course+ ) >
<!ATTLIST courseCatalog campus CDATA #REQUIRED >
<!ATTLIST courseCatalog term CDATA #REQUIRED >
<!ATTLIST courseCatalog year CDATA #REQUIRED >

<!ELEMENT courseCredit EMPTY >
<!ATTLIST courseCredit creditFormat ( arrangeHours | fixedUnit | variableMinMax | variableRange ) #REQUIRED >
<!ATTLIST courseCredit creditType ( collegiate | equivalent | mastersCredit | phdThesisCredit ) #REQUIRED >
<!ATTLIST courseCredit creditUnitType CDATA #REQUIRED >
<!ATTLIST courseCredit fixedCredit CDATA #IMPLIED >
<!ATTLIST courseCredit fractionalCreditAllowed ( false | False | true | True ) #IMPLIED >
<!ATTLIST courseCredit maximumCredit CDATA #IMPLIED >
<!ATTLIST courseCredit minimumCredit CDATA #IMPLIED >

<!ELEMENT subpartCredit EMPTY >
<!ATTLIST subpartCredit creditFormat ( arrangeHours | fixedUnit | variableMinMax | variableRange ) #REQUIRED >
<!ATTLIST subpartCredit creditType ( collegiate | equivalent | mastersCredit | phdThesisCredit ) #REQUIRED >
<!ATTLIST subpartCredit creditUnitType CDATA #REQUIRED >
<!ATTLIST subpartCredit fixedCredit CDATA #IMPLIED >
<!ATTLIST subpartCredit fractionalCreditAllowed ( false | False | true | True ) #IMPLIED >
<!ATTLIST subpartCredit maximumCredit CDATA #IMPLIED >
<!ATTLIST subpartCredit minimumCredit CDATA #IMPLIED >
<!ATTLIST subpartCredit subpartId CDATA #REQUIRED >

=== Jenner4S/unitimes/Documentation/Interfaces/Examples/courseCatalogImport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE courseCatalog PUBLIC "-//UniTime//DTD University Course Timetabling/EN" "http://www.unitime.org/interface/CourseCatalog.dtd">

<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->

	<!-- course          ==> Required:  subject, courseNumber, title
	                         Optional:  externalId, approvalType, permanentId, previousSubject, previousCourseNumber
	                         Deprecated: designatorRequired (since UniTime 3.4)
	       courseCredit  ==> Required:  creditType, creditUnitType, creditFormat
                                        fixedCredit or (minimumCredit and maximumCredit and fractionalCreditAllowed)
           subpartCredit ==> [0 ==> N entries]
	                         Required:  subpartId, creditType, creditUnitType, creditFormat
                                        fixedCredit or (minimumCredit and maximumCredit and fractionalCreditAllowed)
	     
	     approvalType = instructor, department or timeblock
	     creditFormat = arrangeHours, fixedUnit, variableMinMax, variableRange
	     creditType = collegiate, equivalent, mastersCredit, phdThesisCredit
	     designatorRequired = T or F (deprecated in UniTime 3.4, required in UniTime 3.3 or earlier)
	     fractionalCreditAllowed = T or F
	-->
<courseCatalog campus="puWestLafayetteTrdtn" term="Fal" year="2007">
	<course externalId="19RIWK1BZ6LAJ1GXBP2M" subject="A&amp;AE" courseNumber="190" title="Introduction To Aerospace Engineering" permanentId="98" previousSubject="A&amp;AE" previousCourseNumber="190" designatorRequired="False">
  		<courseCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="2"/>
  		<subpartCredit subpartId="10" creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="1"/>
  		<subpartCredit subpartId="30" creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="1"/>
	</course>
  	<course externalId="19RIWX1BZ64JI1GXBP2N" subject="A&amp;AE" courseNumber="203" title="Aeromechanics I" permanentId="100" previousSubject="A&amp;AE" previousCourseNumber="203" designatorRequired="False">
    	<courseCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="3"/>
    	<subpartCredit subpartId="10" creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="3"/>
	</course>
  	<course externalId="19RRWF1CO09LX1HLE8KV" subject="A&amp;AE" courseNumber="590" title="Projects In Aeronautical Engineering" permanentId="158" approvalType="instructor" previousSubject="A&amp;AE" previousCourseNumber="590" designatorRequired="True">
    	<courseCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="variableRange" minimumCredit="1" maximumCredit="6" fractionalCreditAllowed="True"/>
    	<subpartCredit subpartId="80" creditType="collegiate" creditUnitType="semesterHours" creditFormat="variableRange" minimumCredit="1" maximumCredit="6" fractionalCreditAllowed="True"/>
  	</course>
</courseCatalog>
