=== Jenner4S/unitimes/Documentation/Interfaces/EventLoad.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->

<!ELEMENT eventContact EMPTY >
<!ATTLIST eventContact email CDATA #IMPLIED >
<!ATTLIST eventContact externalId NMTOKEN #REQUIRED >
<!ATTLIST eventContact firstName NMTOKEN #IMPLIED >
<!ATTLIST eventContact lastName NMTOKEN #REQUIRED >
<!ATTLIST eventContact middleName NMTOKEN #IMPLIED >
<!ATTLIST eventContact phone NMTOKEN #IMPLIED >

<!ELEMENT course EMPTY >
<!ATTLIST course courseExternalId NMTOKEN #IMPLIED >
<!ATTLIST course relatedExternalId NMTOKEN #REQUIRED >
<!ATTLIST course relationshipType ( class | instructionalOffering | courseOffering ) #REQUIRED >
<!ATTLIST course term NMTOKEN #REQUIRED >
<!ATTLIST course year NMTOKEN #REQUIRED >

<!ELEMENT courseRelatedEvent ( ( meetings | relatedCourses | eventContact? | sponsoringOrganization? | notes? )* ) >
<!ATTLIST courseRelatedEvent attendanceRequired ( false | true ) #IMPLIED >  <!-- defaults to false -->
<!ATTLIST courseRelatedEvent email CDATA #IMPLIED >
<!ATTLIST courseRelatedEvent eventName CDATA #REQUIRED >
<!ATTLIST courseRelatedEvent maxCapacity NMTOKEN #IMPLIED >
<!ATTLIST courseRelatedEvent minCapacity NMTOKEN #IMPLIED >

<!ELEMENT events ( specialEvent | courseRelatedEvent )* >
<!ATTLIST events academicInitiative NMTOKEN #REQUIRED >
<!ATTLIST events created CDATA #REQUIRED >
<!ATTLIST events dateFormat CDATA #REQUIRED >
<!ATTLIST events timeFormat NMTOKEN #REQUIRED >

<!ELEMENT meeting EMPTY >
<!ATTLIST meeting approvedDateTime CDATA #IMPLIED >
<!ATTLIST meeting buildingAbbv NMTOKEN #IMPLIED >
<!ATTLIST meeting classCanOverride ( false | true ) #IMPLIED >  <!-- defaults to true -->
<!ATTLIST meeting stopOffset NMTOKEN #IMPLIED >  
<!ATTLIST meeting endTime NMTOKEN #REQUIRED >
<!ATTLIST meeting location CDATA #IMPLIED >
<!ATTLIST meeting meetingDate CDATA #REQUIRED >
<!ATTLIST meeting roomNumber NMTOKEN #IMPLIED >
<!ATTLIST meeting startOffset NMTOKEN #IMPLIED >
<!ATTLIST meeting startTime NMTOKEN #REQUIRED >

<!ELEMENT meetings ( meeting+ ) >

<!ELEMENT note EMPTY >
<!ATTLIST note noteText CDATA #REQUIRED >
<!ATTLIST note noteType ( create | update | approve | reject | delete | edit ) #REQUIRED >
<!ATTLIST note timestamp CDATA #IMPLIED >
<!ATTLIST note userName CDATA #IMPLIED >  

<!ELEMENT notes ( note+ ) >

<!ELEMENT relatedCourses ( course+ ) >

<!ELEMENT specialEvent ( ( meetings | eventContact | sponsoringOrganization? | notes? )* ) >
<!ATTLIST specialEvent email CDATA #IMPLIED >
<!ATTLIST specialEvent eventName CDATA #REQUIRED >
<!ATTLIST specialEvent maxCapacity NMTOKEN #IMPLIED >
<!ATTLIST specialEvent minCapacity NMTOKEN #IMPLIED >

<!ELEMENT sponsoringOrganization EMPTY >
<!ATTLIST sponsoringOrganization name CDATA #REQUIRED >

=== Jenner4S/unitimes/Documentation/Interfaces/Examples/eventLoad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE events PUBLIC "-//UniTime//DTD University Course Timetabling/EN" "http://www.unitime.org/interface/EventLoad.dtd">

<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 
<events academicInitiative="PWL" created="01/05/2009 15:40:49" dateFormat="MM/dd/yyyy" timeFormat="H:mm">
  	<specialEvent eventName="Special Event 1" minCapacity="10" maxCapacity="15" email="main@contact.email.edu" >
		<sponsoringOrganization name="Sponsoring Org"/>
		<eventContact externalId="1234567890" email="contact@email.edu" phone="555-4444" firstName="FirstName" middleName="MiddleName" lastName="LastName" />
		<meetings>
 			<meeting meetingDate="01/15/2009" startTime="8:00" startOffset="10" endTime="9:00" stopOffset="10" buildingAbbv="WTHR" roomNumber="160" classCanOverride="true" approvedDateTime="01/04/2009 10:00"/>
  			<meeting meetingDate="01/16/2009" startTime="8:00" endTime="9:00" buildingAbbv="WTHR" roomNumber="160" classCanOverride="true" approvedDateTime="01/04/2009 10:00"/>
			<meeting meetingDate="01/21/2009" startTime="8:00" endTime="9:00" buildingAbbv="WTHR" roomNumber="360" classCanOverride="true" approvedDateTime="01/04/2009 10:00"/>
			<meeting meetingDate="01/22/2009" startTime="8:00" endTime="9:00" location="CL50 East" classCanOverride="true" approvedDateTime="01/04/2009 10:00"/>
		</meetings>
	<notes>
	 	<note noteText="This is a note." noteType="create" timestamp="01/04/2009 10:00" userName="Name Of User Who Left Note" />
		<note noteText="This is another note." noteType="create" timestamp="01/04/2009 10:00" userName="Name Of User Who Left Note" />
	</notes>
	</specialEvent>
 	<courseRelatedEvent eventName="Course Related Event 1" minCapacity="10" maxCapacity="15" attendanceRequired="true" email="main@contact.email.edu" >
	  <relatedCourses>
	    <course year="2009" term="Spring" relationshipType="class" relatedExternalId="12345" courseExternalId="CHM11100"/>
	    <course year="2009" term="Spring" relationshipType="instructionalOffering" relatedExternalId="CHM11200" courseExternalId="CHM11200"/>
	    <course year="2009" term="Spring" relationshipType="courseOffering" relatedExternalId="CHM11500" courseExternalId="CHM11500"/>
	  </relatedCourses>
		<sponsoringOrganization name="Sponsoring Org"/>
		<eventContact externalId="1234567890" email="contact@email.edu" phone="555-4444" firstName="FirstName" middleName="MiddleName" lastName="LastName" />
 		<meetings>
	 		<meeting meetingDate="01/17/2009" startTime="20:00" endTime="21:00" buildingAbbv="WTHR" roomNumber="160" classCanOverride="true" approvedDateTime="01/04/2009 10:00"/>
			<meeting meetingDate="01/19/2009" startTime="8:30" endTime="9:30" buildingAbbv="WTHR" roomNumber="160" classCanOverride="false" approvedDateTime="01/04/2009 18:00"/>
			<meeting meetingDate="01/26/2009" startTime="20:30" endTime="21:30" buildingAbbv="WTHR" roomNumber="360" classCanOverride="false" approvedDateTime="01/04/2009 18:00"/>
			<meeting meetingDate="01/27/2009" startTime="8:00" endTime="9:00" location="CL50 East" classCanOverride="true" approvedDateTime="01/04/2009 10:00"/>
		</meetings>
	</courseRelatedEvent>
  	<specialEvent eventName="Special Event 2" >
		<meetings>
			<meeting meetingDate="02/15/2009" startTime="8:00" endTime="9:00" buildingAbbv="WTHR" roomNumber="160" classCanOverride="true" approvedDateTime="01/04/2009 10:00"/>
		</meetings>
		<eventContact externalId="1234567890" email="contact@email.edu" phone="555-4444" firstName="FirstName" middleName="MiddleName" lastName="LastName" />
	</specialEvent>
 	<courseRelatedEvent eventName="Course Related Event 2" attendanceRequired="true" email="main@contact.email.edu" >
	  <relatedCourses>
	    <course year="2009" term="Spring" relationshipType="class" relatedExternalId="12345" courseExternalId="CHM11100"/>
	  </relatedCourses>
		<meetings>
			<meeting meetingDate="02/17/2009" startTime="9:00"  endTime="10:00" buildingAbbv="WTHR" roomNumber="160" classCanOverride="false"/>
		</meetings>
	</courseRelatedEvent>
</events>
