=== Jenner4S/unitimes/Documentation/Interfaces/Preferences.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->

<!ELEMENT preferences ((department|instructor|subpart|class)*) >
<!ATTLIST preferences campus CDATA #REQUIRED >
<!ATTLIST preferences term CDATA #REQUIRED >
<!ATTLIST preferences year CDATA #REQUIRED >
<!ATTLIST preferences created CDATA #IMPLIED >
<!ATTLIST preferences timeFormat CDATA #IMPLIED >
<!ATTLIST preferences dateFormat CDATA #IMPLIED >

<!ELEMENT department ((timePref|roomPref|buildingPref|groupPref|featurePref|datePref|distributionPref)*) >
<!ATTLIST department code CDATA #REQUIRED >

<!ELEMENT instructor ((timePref|roomPref|buildingPref|groupPref|featurePref|datePref|distributionPref|coursePref|teachingPref)*) >
<!ATTLIST instructor externalId CDATA #IMPLIED >
<!ATTLIST instructor firstName CDATA #IMPLIED >
<!ATTLIST instructor lastName CDATA #IMPLIED >
<!ATTLIST instructor middleName CDATA #IMPLIED >
<!ATTLIST instructor department CDATA #REQUIRED >
<!ATTLIST instructor email CDATA #IMPLIED >
<!ATTLIST instructor title CDATA #IMPLIED >

<!ELEMENT subpart ((timePref|roomPref|buildingPref|groupPref|featurePref|datePref)*) >
<!ATTLIST subpart subject CDATA #REQUIRED >
<!ATTLIST subpart course CDATA #REQUIRED >
<!ATTLIST subpart config CDATA #IMPLIED >
<!ATTLIST subpart type CDATA #IMPLIED >
<!ATTLIST subpart suffix CDATA #IMPLIED >
<!ATTLIST subpart pattern CDATA #IMPLIED >

<!ELEMENT class ((timePref|roomPref|buildingPref|groupPref|featurePref|datePref)*) >
<!ATTLIST class subject CDATA #REQUIRED >
<!ATTLIST class course CDATA #REQUIRED >
<!ATTLIST class externalId CDATA #IMPLIED >
<!ATTLIST class type CDATA #IMPLIED >
<!ATTLIST class suffix CDATA #IMPLIED >
<!ATTLIST class pattern CDATA #IMPLIED >

<!ELEMENT roomPref EMPTY >
<!ATTLIST roomPref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST roomPref building CDATA #IMPLIED >
<!ATTLIST roomPref room CDATA #IMPLIED >
<!ATTLIST roomPref location CDATA #IMPLIED >

<!ELEMENT buildingPref EMPTY >
<!ATTLIST buildingPref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST buildingPref building CDATA #REQUIRED >

<!ELEMENT groupPref EMPTY >
<!ATTLIST groupPref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST groupPref group CDATA #REQUIRED >
<!ATTLIST groupPref department CDATA #IMPLIED >

<!ELEMENT featurePref EMPTY >
<!ATTLIST featurePref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST featurePref feature CDATA #REQUIRED >
<!ATTLIST featurePref department CDATA #IMPLIED >

<!ELEMENT datePref EMPTY >
<!ATTLIST datePref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST datePref pattern CDATA #REQUIRED >

<!ELEMENT distributionPref ((class|subpart)*) >
<!ATTLIST distributionPref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST distributionPref type CDATA #REQUIRED >
<!ATTLIST distributionPref structure (AllClasses|Progressive|GroupsOfTwo|GroupsOfThree|GroupsOfFour|GroupsOfFive|Pairwise|OneOfEach) #IMPLIED >

<!ELEMENT timePref (pref*) >
<!ATTLIST timePref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST timePref pattern CDATA #IMPLIED >

<!ELEMENT pref EMPTY >
<!ATTLIST pref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST pref day CDATA #IMPLIED >
<!ATTLIST pref days CDATA #IMPLIED >
<!ATTLIST pref start CDATA #IMPLIED >
<!ATTLIST pref stop CDATA #IMPLIED >
<!ATTLIST pref time CDATA #IMPLIED >

<!ELEMENT coursePref EMPTY >
<!ATTLIST coursePref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST coursePref subject CDATA #REQUIRED >
<!ATTLIST coursePref course CDATA #REQUIRED >

<!ELEMENT attributePref EMPTY >
<!ATTLIST attributePref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST attributePref attribute CDATA #REQUIRED >

<!ELEMENT instructorPref EMPTY >
<!ATTLIST instructorPref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST instructorPref instructor CDATA #REQUIRED >

<!ELEMENT teachingPref EMPTY >
<!ATTLIST teachingPref level ( R | -2 | -1 | 0 | 1 | 2 | P ) #REQUIRED >
<!ATTLIST teachingPref maxLoad CDATA #REQUIRED >

=== Jenner4S/unitimes/Documentation/Interfaces/Examples/preferences.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE preferences PUBLIC "-//UniTime//UniTime Preferences/EN" "http://www.unitime.org/interface/Preferences.dtd">

<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 <preferences term="Fal" year="2010" campus="woebegon" dateFormat="yyyy/M/d" timeFormat="HHmm" created="Wed Mar 08 08:56:15 CET 2017">
  <department code="0100">
    <roomPref building="THTR" room="101" level="P"/>
    <roomPref building="EDUC" room="101" level="0"/>
  </department>
  <department code="0101">
    <distributionPref type="SAME_ROOM" structure="Progressive" level="-1">
      <subpart subject="CHM" course="101" type="Lec"/>
      <subpart subject="CHM" course="101" type="Lab"/>
      <subpart subject="CHM" course="101" type="Rec"/>
    </distributionPref>
    <distributionPref type="SAME_DAYS" structure="AllClasses" level="-2">
      <class subject="CHM" course="101" type="Rec" suffix="1"/>
      <class subject="CHM" course="101" type="Rec" suffix="2"/>
      <class subject="CHM" course="101" type="Rec" suffix="5"/>
    </distributionPref>
    <roomPref building="EDUC" room="103" level="0"/>
    <roomPref building="EDUC" room="102" level="0"/>
    <roomPref building="EDUC" room="105" level="P"/>
    <distributionPref type="PRECEDENCE" structure="AllClasses" level="R">
      <subpart subject="COM" course="101" type="Lec"/>
    </distributionPref>
    <roomPref building="EDUC" room="104" level="0"/>
    <roomPref building="EDUC" room="108" level="0"/>
    <roomPref building="EDUC" room="106" level="0"/>
    <roomPref building="THTR" room="101" level="2"/>
    <roomPref building="EDUC" room="107" level="0"/>
    <roomPref building="EDUC" room="101" level="0"/>
  </department>
  <department code="0102">
    <roomPref location="MALL" level="0"/>
  </department>
  <instructor externalId="100" firstName="JOE" lastName="DOE" department="0101">
  	<teachingPref maxLoad="20.0" level="0"/>
    <featurePref feature="Comp" level="-2"/>
    <timePref level="R">
      <pref level="P" day="M" start="0730" stop="0830"/>
      <pref level="-2" day="M" start="0930" stop="1430"/>
      <pref level="P" day="T" start="0730" stop="0830"/>
      <pref level="2" day="T" start="0830" stop="1830"/>
      <pref level="P" day="W" start="0730" stop="0830"/>
      <pref level="-2" day="W" start="0930" stop="1430"/>
      <pref level="P" day="R" start="0730" stop="0830"/>
      <pref level="2" day="R" start="0830" stop="1830"/>
      <pref level="P" day="F" start="0730" stop="0830"/>
      <pref level="-2" day="F" start="0930" stop="1430"/>
      <pref level="P" day="F" start="1600" stop="1830"/>
    </timePref>
    <distributionPref type="MAX_HRS_DAY(6)" structure="AllClasses" level="-2"/>
    <coursePref subject="ALG" course="101" level="-2"/>
  </instructor>
  <instructor externalId="101" firstName="GEORGE" lastName="NEWMAN" department="0101">
    <timePref level="R">
      <pref level="2" day="M" start="0730" stop="0830"/>
      <pref level="1" day="M" start="0830" stop="1830"/>
      <pref level="P" day="M" start="2300" stop="2400"/>
      <pref level="2" day="T" start="0730" stop="0830"/>
      <pref level="-2" day="T" start="0930" stop="1330"/>
      <pref level="2" day="W" start="0730" stop="0830"/>
      <pref level="-1" day="W" start="0930" stop="1330"/>
      <pref level="2" day="R" start="0730" stop="0830"/>
      <pref level="-2" day="R" start="0930" stop="1330"/>
      <pref level="2" day="F" start="0730" stop="0830"/>
      <pref level="1" day="F" start="0830" stop="1830"/>
    </timePref>
    <buildingPref building="EDUC" level="-2"/>
    <featurePref feature="ThtrSeat" level="P"/>
    <distributionPref type="_MaxDays:3_" structure="AllClasses" level="R"/>
  </instructor>
  <instructor externalId="102" firstName="JOHN" middleName="WILLIAM" lastName="SMITH" department="0101">
    <timePref level="R">
      <pref level="2" day="M" start="0730" stop="0830"/>
      <pref level="1" day="M" start="1630" stop="1830"/>
      <pref level="2" day="T" start="0730" stop="0830"/>
      <pref level="1" day="T" start="1630" stop="1830"/>
      <pref level="2" day="W" start="0730" stop="0830"/>
      <pref level="1" day="W" start="1630" stop="1830"/>
      <pref level="2" day="R" start="0730" stop="0830"/>
      <pref level="1" day="R" start="1630" stop="1830"/>
      <pref level="2" day="F" start="0730" stop="0830"/>
      <pref level="1" day="F" start="1630" stop="1830"/>
    </timePref>
  </instructor>
  <instructor firstName="JOHN" lastName="STUDENT" department="0101"/>
  <instructor firstName="STEVEN" lastName="STUDENT" department="0101"/>
  <subpart subject="ALG" course="101" type="Lec">
    <groupPref group="Classroom" level="R"/>
    <timePref pattern="2 x 75" level="R">
      <pref level="P" days="TR" time="0730"/>
      <pref level="P" days="TR" time="0900"/>
      <pref level="P" days="TR" time="1030"/>
      <pref level="P" days="TR" time="1200"/>
      <pref level="P" days="TR" time="1330"/>
      <pref level="P" days="TR" time="1500"/>
      <pref level="P" days="TR" time="1630"/>
    </timePref>
    <timePref pattern="3 x 50" level="R"/>
  </subpart>
  <class subject="ALG" course="101" type="Lec" suffix="1"/>
  <subpart subject="BAND" course="101" type="Lec">
    <timePref pattern="5 x 100" level="R">
      <pref level="-2" days="MTWRF" time="1530"/>
    </timePref>
  </subpart>
  <class subject="BAND" course="101" type="Lec" suffix="1"/>
  <subpart subject="BIOL" course="101" type="Lec">
    <timePref pattern="2 x 50" level="R"/>
  </subpart>
  <class subject="BIOL" course="101" type="Lec" suffix="1"/>
  <class subject="BIOL" course="101" type="Lec" suffix="2"/>
  <class subject="BIOL" course="101" type="Lec" suffix="3"/>
  <subpart subject="BIOL" course="101" type="Lab">
    <timePref pattern="1 x 100" level="R">
      <pref level="P" days="M" time="0730"/>
      <pref level="P" days="M" time="0930"/>
      <pref level="P" days="M" time="1130"/>
      <pref level="P" days="M" time="1330"/>
      <pref level="P" days="M" time="1530"/>
      <pref level="P" days="T" time="0730"/>
      <pref level="P" days="T" time="0930"/>
      <pref level="P" days="T" time="1130"/>
      <pref level="P" days="T" time="1330"/>
      <pref level="P" days="T" time="1530"/>
    </timePref>
    <groupPref group="Biol Labs" department="0101" level="R"/>
  </subpart>
  <class subject="BIOL" course="101" type="Lab" suffix="1"/>
  <class subject="BIOL" course="101" type="Lab" suffix="2"/>
  <class subject="BIOL" course="101" type="Lab" suffix="3"/>
  <class subject="BIOL" course="101" type="Lab" suffix="4"/>
  <class subject="BIOL" course="101" type="Lab" suffix="5"/>
  <class subject="BIOL" course="101" type="Lab" suffix="6"/>
  <class subject="BIOL" course="101" type="Lab" suffix="7"/>
  <class subject="BIOL" course="101" type="Lab" suffix="8"/>
  <class subject="BIOL" course="101" type="Lab" suffix="9"/>
  <class subject="BIOL" course="101" type="Lab" suffix="10"/>
  <class subject="BIOL" course="101" type="Lab" suffix="11"/>
  <subpart subject="BIOL" course="101" type="Rec">
    <groupPref group="Classroom" level="R"/>
    <timePref pattern="1 x 50" level="R"/>
  </subpart>
  <class subject="BIOL" course="101" type="Rec" suffix="1"/>
  <class subject="BIOL" course="101" type="Rec" suffix="2"/>
  <class subject="BIOL" course="101" type="Rec" suffix="3"/>
  <class subject="BIOL" course="101" type="Rec" suffix="4"/>
  <class subject="BIOL" course="101" type="Rec" suffix="5"/>
  <class subject="BIOL" course="101" type="Rec" suffix="6"/>
  <class subject="BIOL" course="101" type="Rec" suffix="7"/>
  <class subject="BIOL" course="101" type="Rec" suffix="8"/>
  <class subject="BIOL" course="101" type="Rec" suffix="9"/>
  <class subject="BIOL" course="101" type="Rec" suffix="10"/>
  <class subject="BIOL" course="101" type="Rec" suffix="11"/>
  <subpart subject="BIOL" course="101" type="Pso">
    <timePref pattern="1 x 50" level="R"/>
  </subpart>
  <class subject="BIOL" course="101" type="Pso" suffix="1"/>
  <class subject="BIOL" course="101" type="Pso" suffix="2"/>
  <class subject="BIOL" course="101" type="Pso" suffix="3"/>
  <subpart subject="BIOL" course="201" type="Lec">
    <groupPref group="Classroom" level="R"/>
    <timePref pattern="2 x 50" level="R"/>
  </subpart>
  <subpart subject="BIOL" course="201" type="Lab">
    <timePref pattern="1 x 100" level="R">
      <pref level="P" days="M" time="0730"/>
      <pref level="P" days="T" time="0730"/>
      <pref level="P" days="W" time="0730"/>
      <pref level="P" days="R" time="0730"/>
      <pref level="P" days="F" time="0730"/>
    </timePref>
    <groupPref group="Classroom" level="R"/>
  </subpart>
  <subpart subject="C S" course="101" type="Lab">
    <groupPref group="Comp Labs" department="0101" level="R"/>
    <timePref pattern="1 x 100" level="R"/>
  </subpart>
  <class subject="C S" course="101" type="Lab" suffix="1"/>
  <class subject="C S" course="101" type="Lab" suffix="2"/>
  <class subject="C S" course="101" type="Lab" suffix="3"/>
  <class subject="C S" course="101" type="Lab" suffix="4"/>
  <subpart subject="C S" course="101" type="Lec">
    <timePref pattern="2 x 50" level="R"/>
