=== Jenner4S/unitimes/Documentation/Interfaces/RoomAvailability.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->

<!ELEMENT parameters ( year, term, campus, beginDate, endDate, startTime, endTime ) >
<!ATTLIST parameters created CDATA #REQUIRED >

<!ELEMENT year EMPTY >
<!ATTLIST year value CDATA #REQUIRED >

<!ELEMENT term EMPTY >
<!ATTLIST term value CDATA #REQUIRED >

<!ELEMENT campus EMPTY >
<!ATTLIST campus value CDATA #REQUIRED >

<!ELEMENT beginDate EMPTY >
<!ATTLIST beginDate value CDATA #REQUIRED >

<!ELEMENT endDate EMPTY >
<!ATTLIST endDate value CDATA #REQUIRED >

<!ELEMENT startTime EMPTY >
<!ATTLIST startTime value CDATA #REQUIRED >

<!ELEMENT endTime EMPTY >
<!ATTLIST endTime value CDATA #REQUIRED >

<!ELEMENT availability ( room* ) >
<!ATTLIST availability created CDATA #REQUIRED >
<!ATTLIST availability dateFormat CDATA #REQUIRED >
<!ATTLIST availability timeFormat CDATA #REQUIRED >

<!ELEMENT room ( event* ) >
<!ATTLIST room externalId CDATA #IMPLIED >
<!ATTLIST room building CDATA #REQUIRED >
<!ATTLIST room roomNbr CDATA #REQUIRED >

<!ELEMENT event EMPTY >
<!ATTLIST event name CDATA #REQUIRED >
<!ATTLIST event type CDATA #REQUIRED >
<!ATTLIST event date CDATA #REQUIRED >
<!ATTLIST event startTime CDATA #REQUIRED >
<!ATTLIST event endTime CDATA #REQUIRED >

<!ATTLIST sessionDates examBegin CDATA #IMPLIED >
<!ATTLIST sessionDates eventBegin CDATA #IMPLIED >
<!ATTLIST sessionDates eventEnd CDATA #IMPLIED >

=== Jenner4S/unitimes/Documentation/Interfaces/Examples/roomAvailabilityResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE availability PUBLIC "-//UniTime//UniTime Room Availability DTD/EN" "http://www.unitime.org/interface/RoomAvailability.dtd">

<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 
<availability created="Tue Sep 27 14:47:54 CEST 2011" dateFormat="MM/dd/yyyy" timeFormat="H:mm">
	<room externalId="T101" building="THTR" roomNbr="101">
		<event name="Performances" type="Special" date="12/13/2010" startTime="8:00" endTime="10:00"/>
		<event name="Performances" type="Special" date="12/15/2010" startTime="8:00" endTime="10:00"/>
	</room>
	<room externalId="E102" building="EDUC" roomNbr="102">
		<event name="Meeting" type="Special" date="12/15/2010" startTime="9:00" endTime="10:20"/>
		<event name="Room Not Available" type="Maintenance" date="12/16/2010" startTime="12:00" endTime="16:00"/>
	</room>
	<room building="EDUC" roomNbr="103">
		<event name="Joe's Birthday" type="Special" date="12/15/2010" startTime="15:00" endTime="20:00"/>
	</room>
	<room building="EDUC" roomNbr="104">
		<event name="Staff Lunch" type="Special" date="12/13/2010" startTime="12:00" endTime="12:30"/>
		<event name="Staff Lunch" type="Special" date="12/14/2010" startTime="12:00" endTime="12:30"/>
		<event name="Staff Lunch" type="Special" date="12/15/2010" startTime="12:00" endTime="12:30"/>
		<event name="Staff Lunch" type="Special" date="12/16/2010" startTime="12:00" endTime="12:30"/>
	</room>
</availability>

=== Jenner4S/unitimes/Documentation/Interfaces/Examples/roomAvailabilityRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE parameters PUBLIC "-//UniTime//UniTime Room Availability DTD/EN" "http://www.unitime.org/interface/RoomAvailability.dtd">

<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 
 <parameters created="Tue Sep 27 14:47:23 CEST 2011">
  <year value="2010"/>
  <term value="Fal"/>
  <campus value="woebegon"/>
  <beginDate value="12/13/2010"/>
  <endDate value="12/16/2010"/>
  <startTime value="08:00"/>
  <endTime value="16:00"/>
</parameters>
