=== Jenner4S/unitimes/Documentation/Interfaces/StudentScheduling_3_4.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 
<!--
 - Student Scheduling XML interface
   - this interface is to be used to synchronize student information with an external system during (online) student scheduling
   - it also contains ability for the external system to approve / reject changes in student's schedule (an ability of a student to get into a course)
 - See studentSchedulingSynchronization.xml for an example and a desription.
 - Since UniTime 3.4
-->
 
<!ELEMENT message (student+) >
<!ATTLIST message id CDATA #REQUIRED >
<!ATTLIST message repliesTo CDATA #IMPLIED >
<!ATTLIST message created CDATA #REQUIRED >
<!ATTLIST message type ( student_change | approval_request | approval | consent | synchronization | schedule_change  ) #REQUIRED >
<!ATTLIST message source ( assistant | waitlist | course_change | dashboard | synchronization | student_change )  #IMPLIED >
<!ATTLIST message tsformat CDATA #IMPLIED >
<!ATTLIST message campus CDATA #REQUIRED >
<!ATTLIST message term CDATA #REQUIRED >
<!ATTLIST message year CDATA #REQUIRED >

<!ELEMENT student (curriculum*, group*, course*) >
<!ATTLIST student id CDATA #REQUIRED >
<!ATTLIST student first CDATA #IMPLIED >
<!ATTLIST student middle CDATA #IMPLIED >
<!ATTLIST student last CDATA #IMPLIED >
<!ATTLIST student email CDATA #IMPLIED >
<!ATTLIST student status CDATA #IMPLIED >
<!ATTLIST student statusTimestamp CDATA #IMPLIED >

<!ELEMENT curriculum EMPTY >
<!ATTLIST curriculum area CDATA #REQUIRED >
<!ATTLIST curriculum major CDATA #REQUIRED >
<!ATTLIST curriculum minor CDATA #IMPLIED >
<!ATTLIST curriculum classification CDATA #REQUIRED >

<!ELEMENT group EMPTY >
<!ATTLIST group code CDATA #REQUIRED >

<!ELEMENT course (class*, reservation?) >
<!ATTLIST course subject CDATA #REQUIRED >
<!ATTLIST course number CDATA #REQUIRED >
<!ATTLIST course status CDATA #IMPLIED >
<!ATTLIST course statusTimestamp CDATA #IMPLIED >
<!ATTLIST course message CDATA #IMPLIED >
<!ATTLIST course consent CDATA #IMPLIED >
<!ATTLIST course consentUserId CDATA #IMPLIED >
<!ATTLIST course consentTimestamp CDATA #IMPLIED >
<!ATTLIST course requestUserId CDATA #IMPLIED >
<!ATTLIST course requestTimestamp CDATA #IMPLIED >

<!ELEMENT reservation ( #PCDATA ) >
<!ATTLIST reservation type ( Individual | Curriculum | Group | Course ) #REQUIRED >
<!ATTLIST reservation allowOverLimit ( true | false ) #REQUIRED >
<!ATTLIST reservation allowTimeOverlap ( true | false ) #REQUIRED >

<!ELEMENT class ( #PCDATA ) >
<!ATTLIST class id CDATA #IMPLIED >
<!ATTLIST class allowTimeOverlap ( true | false ) #IMPLIED >
<!ATTLIST class message CDATA #IMPLIED >

=== Jenner4S/unitimes/Documentation/Interfaces/Examples/studentSchedulingSynchronization.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE message PUBLIC "-//UniTime//Student Sectioning Interface/EN" "../StudentScheduling_3_4.dtd">
<!-- 
<!DOCTYPE message PUBLIC "-//UniTime//Student Sectioning Interface/EN" "http://www.unitime.org/interface/StudentScheduling_3_4.dtd">
 -->
 
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 
 <!--
 - Student Scheduling XML interface
   - this interface is to be used to synchronize student information with an external system during (online) student scheduling
   - it also contains ability for the external system to approve / reject changes in student's schedule (an ability of a student to get into a course)
 - Since UniTime 3.4
-->

<message id="10234" repliesTo="10232" created="2012/04/17 6:46:10" type="schedule_change" source="assistant" tsformat="yyyy/MM/dd HH:mm:ss" campus="PWL" year="2013" term="Spring">
    <!-- id .. generated unique message id -->
    <!-- repliesTo .. if the message is a response to some other message, this contains id of the other message -->
    <!-- created .. time stamp in some given format -->
    <!-- type .. message type: schedule change, approval request, consent, synchronization, approval, student change -->
    <!-- source .. message source (for UniTime side): assistant, wait-list, course change, dashboard, nightly synchronization, student change (optional) -->
    <!-- tsformat .. time stamp format -->
    <student id="120345679" first="Joe" middle="Franklin" last="Doe" email="doe@university.edu" status="scheduling" statusTimestamp="2012/04/01 12:23:23">
        <!-- id .. student external id -->
        <!-- first, middle, last .. student name -->
        <!-- email .. student email -->
        <!-- status .. student status reference -->
        <!-- statusTimestamp .. time of the last student status change, not sure if this field will be useful, but leaving it in for audit trail -->
        <curriculum area="A" major="VSC" classification="01"/>
        <!-- curriculum information, multiple curricula can be provided -->
        <group code="YngExpl"/>
        <!-- multiple student groups may be present -->
        
        <!-- student schedule: -->
        <course subject="AAE" number="20300" status="approved" statusTimestamp="2012/04/14 17:12:10" requestUserId="120345679" requestTimestamp="2012/04/14 17:11:10" >
            <class id="12456"/>
            <class id="12424"/>
            <!-- subject, number .. course identification -->
            <!-- status .. approval status: 
                       approved - sent by SIS to UniTime to indicate it successfully enrolled the student in all parts of the course
                                - sent by UniTime to SIS to indicate it has sent this specific course request in the past and the request
                                    was successful in SIS.  
                       pending - sent by SIS to UniTime to indicate the student request for this course has not been approved yet because
                                    it is waiting on some type of consent or other approval.  UniTime will hold the student's space in the
                                    course and resend the request later to see if the consent or other approval has been granted.
                               - sent by UniTime to SIS to indicate UniTime previously received a status of pending from the SIS for this
                                    course request.  The SIS should check to see if the appropriate consent or other approval has been granted
                                    respond appropriately. 
                       rejected - only from SIS to UniTime.  If a course is rejected UniTime will not schedule the student the course. -->
            <!--   statuses to be defined in a lookup table, generated by SIS in a response to UniTime approval request / schedule change messages -->
            <!-- statusTimestamp .. time and date the status was received from the SIS, not sure if this is useful, but leaving it in for audit trail -->
            <!-- requestUserId .. the external id of the user who made the request for this course, normally it is the student, however, it could be
                                     an advisor or other person who has rights to schedule a student into a course, likely not used by Banner
                                     but may be useful to a different SIS -->
            <!-- requestTimestamp .. the timestamp the request for the course was made, not sure how useful this is but leaving it in for audit trail -->
            <!-- class id .. external id (CRN) of the class -->
        </course>
        <course subject="ENGL" number="10600R" status="pending" statusTimestamp="2012/04/14 17:12:10" message="Instructor signature needed" requestUserId="120345679" requestTimestamp="2012/04/14 17:11:10" >
            <!-- status, statusTimestamp, message .. last provided status and message (optional) from Banner approval process -->
            <!-- requestUserId, requestTimestamp .. last provided request user external id and request timestamp (optional) for Banner approval process -->
            <class id="23495"/>
            <class id="23454"/>
            <class id="23065"/>
        </course>
        <course subject="BIOL" number="10500" status="reject" message="prereq not met"/>
        <!-- example reject response from SIS -->
        <!-- if message is not provided, the default one from the status lookup table is given -->
        <!-- status lookup table: banner status -> approve / reject / pending + default message to student -->
        <course subject="AD" number="11000" status="reject" message="prereq not met" >
        	<class id="54491" message="prereq not met"/>
        	<class id="76746" message="Instructor signature needed"/>
        </course>	
        <!-- example reject response from SIS -->
        <!-- if the SIS has multiple reject messages that are for different classes in the course, the SIS may return 
                a class element that contains a message for each rejected class-->
        <course subject="CS" number="25400" requestUserId="120345679" requestTimestamp="2012/04/14 17:11:10" >
            <!-- new course (no approval status was provided by Banner yet) -->
            <class id="213435"/>
        </course>
        <course subject="MA" number="15200" requestUserId="120345679" requestTimestamp="2012/04/14 17:11:10" >
            <!-- new course (student placed in lecture over limit) -->
            <class id="75323"/>
            <class id="96853"/>
            <class id="53677"/>
        	<reservation type="Individual" allowOverLimit="true" allowTimeOverlap="false"/>
        	<!-- if reservation is present, Banner must accept all classes in the request -->
        </course>
        <course subject="AAE" number="20400" consent="instructor" consentUserId="23456435" consentTimestamp="2012/04/16 14:23:20" requestUserId="120345679" requestTimestamp="2012/04/14 17:11:10" >
            <class id="231235"/>
            <!-- consent .. instructor, department or other consent as defined in the UniTime consent types table -->
            <!-- consentId .. external id of the person who gave consent -->
            <!-- consentTimestamp .. timestamp representing the time and date the consent was given, not sure if this is useful, but leaving it in for audit trail -->
            <!-- reasoning for this data - the SIS may need to create an appropriate record in its database to give a student the consent or override so we need
                    to provide enough data to allow the SIS to do this. -->
        </course>
        <!-- Do we need to list courses, classes that were removed from student schedule (from UniTime), either by student, automatic scheduling, or by rejecting consent? no 
             - This is always the complete schedule if a course is not in the list the student needs to be removed from the course on the Banner Side 
        -->
        <!-- Do we want to include timestamp?
           when a course was requested
           when a class was given to the student in UniTime
           when approval status was given / changed   - not necessary, Banner does not care, it is useful for UniTime to store, but Banner will do nothing with it.       
        -->
        <!-- Do we want to include external id of the person who did make the change (if it was not automated)? yes
           Or just one of: student, advisor (any person, not student), system (automatic) - no
           This we know on a course request and on the enrollment
         -->
        <!-- Do we want to include priority / alternativity of the course request? no -->
        <!-- Do we want to include wait-listed (not assigned) course requests in the student schedule? no -->
        <course subject="AAE" number="30100" requestUserId="120345679" requestTimestamp="2012/04/16 12:23:12 " consent="department" consentUserId="23456435"  consentTimestamp="2012/04/17 8:12:21" status="approved" statusTimestamp="2012/04/17 8:14:23">
            <class id="340920"/>
        </course>
    </student>
            
    <!-- student schedule change example -->
    <!-- request sent from UniTime -->
