=== Jenner4S/unitimes/Documentation/Interfaces/TravelTimes.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 
<!ELEMENT traveltimes (from*) >
<!ATTLIST traveltimes campus CDATA #REQUIRED >
<!ATTLIST traveltimes term CDATA #REQUIRED >
<!ATTLIST traveltimes year CDATA #REQUIRED >
<!ATTLIST traveltimes created CDATA #IMPLIED >

<!ELEMENT from ( to+ ) >
<!ATTLIST from id CDATA #IMPLIED >
<!ATTLIST from building CDATA #IMPLIED >
<!ATTLIST from roomNbr CDATA #IMPLIED >
<!ATTLIST from name CDATA #IMPLIED >

<!ELEMENT to (#PCDATA) >
<!ATTLIST to id CDATA #IMPLIED >
<!ATTLIST to building CDATA #IMPLIED >
<!ATTLIST to roomNbr CDATA #IMPLIED >
<!ATTLIST to name CDATA #IMPLIED >

=== Jenner4S/unitimes/Documentation/Interfaces/Examples/travelTimes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE traveltimes PUBLIC "-//UniTime//UniTime Travel Times DTD/EN" "http://www.unitime.org/interface/TravelTimes.dtd">

<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 
<traveltimes campus="woebegon" year="2010" term="Fal" created="Fri Nov 09 18:02:57 CET 2012">
  <from building="EDUC" roomNbr="107">
    <to id="THTR101" building="THTR" roomNbr="101">5</to>
    <to name="MALL">10</to>
  </from>
  <from building="EDUC" roomNbr="108">
    <to building="EDUC" roomNbr="101">0</to>
    <to id="THTR101" building="THTR" roomNbr="101">5</to>
    <to name="MALL">10</to>
  </from>
  <from id="THTR101" building="THTR" roomNbr="101">
    <to building="EDUC" roomNbr="101">5</to>
    <to building="EDUC" roomNbr="102">5</to>
    <to building="EDUC" roomNbr="103">5</to>
    <to building="EDUC" roomNbr="104">5</to>
    <to building="EDUC" roomNbr="105">5</to>
    <to building="EDUC" roomNbr="106">5</to>
    <to name="MALL">15</to>
  </from>
  <from name="MALL">
    <to building="EDUC" roomNbr="101">10</to>
    <to building="EDUC" roomNbr="102">10</to>
    <to building="EDUC" roomNbr="103">10</to>
    <to building="EDUC" roomNbr="104">10</to>
    <to building="EDUC" roomNbr="105">10</to>
    <to building="EDUC" roomNbr="106">10</to>
  </from>
</traveltimes>
